### PR TITLE
Fix =)

### PR DESCRIPTION
**Pull request by rgaiacs**

### CODE REVIEW

**Comment by gvwilson** [comment]
-1: people want to be able to write Markdown posts, Jekyll supports it, 
the Data Carpentry site builds with .md posts just fine, so we need to 
figure out why .md isn't included in the build.

**Comment by rgaiacs** [comment]
@gvwilson Just add `2016-01-03-` at the begin of the post. You can write in Markdown. Changed it a few seconds ago.

**Comment by rgaiacs** [comment]
> the Data Carpentry site builds with .md posts just fine, so we need to figure out why .md isn't included in the build.

As I said, you just need to add the date of the post at the begin of the file name. That's the way that Data Carpentry does, https://github.com/datacarpentry/datacarpentry.github.io/tree/master/_posts, and how everyone does.

**Comment by gvwilson** [comment]
Ah - so it *won't* take it from the datestamp inside the post, 
presumably because it's wildcarding on filenames to figure out what to 
build.  I'll fix and push.

**Pull request closed without merging**
